all:
  hosts:
    myserver:
      ansible_host: 3.124.11.70
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../terraform/ssh-keys/uptime_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'